{% set name = "rapunzel" %}
{% set version = "0.5.10" %}
{% set sha256 = "2ac7eeac445be91ea108d3e3a4d0d93c2f5359b234a7aeb8c4ad084ec821ed2b" %}
{% set url = "https://files.pythonhosted.org/packages/6c/92/c9f16161dcb5a6b5f38e91216b9ff4619d04e03826582263711989a7bb7f/rapunzel-0.5.10.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1
  entry_points:
    - rapunzel = rapunzel:rapunzel
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.7a3
    - python-levenshtein
    - qtconsole
    - nbformat
    - psutil
    - pyspellchecker
    - esprima-python

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
