{% set name = "rapunzel" %}
{% set version = "0.5.0" %}
{% set sha256 = "6610d3096600934ddbe93d3024eff89a7e69d0c7049ba329a15897296b400d57" %}
{% set url = "https://files.pythonhosted.org/packages/aa/34/fbcb3bf207a926c5083fdb77864b8e12ed967428404c7e5bf0fc667ac8fe/rapunzel-0.5.0.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1
  entry_points:
    - rapunzel = rapunzel:rapunzel
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.7a3
    - python-levenshtein
    - qtconsole
    - nbformat
    - psutil
    - pyspellchecker
    - esprima-python

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
