{% set name = "python-opensesame" %}
{% set version = "3.3.4a1" %}
{% set sha256 = "5280c1be80ee217916f3656b809c2e81233820a9a1320ee76571e37d25b0cfa5" %}
{% set url = "https://files.pythonhosted.org/packages/59/5e/4af6704d368222387786db66b6f7626403c086e2611241fb3dccb2a3e72e/python-opensesame-3.3.4a1.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.24
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.15.0a4
    - pyqode.python >=2.12.2a10

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
