{% set name = "python-opensesame" %}
{% set version = "3.3.7a4" %}
{% set sha256 = "09c80296a57421fea57e3895e55a26f972f89de02a3e360f6b53e42ec16949b0" %}
{% set url = "https://files.pythonhosted.org/packages/67/e7/0c427be49ca5a81a4e3a0f8e7e43a5816a6203de5a970fbfe86213816ea4/python-opensesame-3.3.7a4.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.24
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=3.1
    - pyqode.python >=3.1

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
