{% set name = "opensesame-extension-language_server" %}
{% set version = "0.1.8" %}
{% set sha256 = "1579d6985f49046c151a5f07a915311e5967857c148fd7972a64b189e56e2d48" %}
{% set url = "https://files.pythonhosted.org/packages/33/b0/e4ed913b6cba7c9f9491de825ea7ff9ad624c712cb465db6d876c5653594/opensesame-extension-language_server-0.1.8.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - pyqode.language_server

  run:
    - python
    - python-opensesame
    - pyyaml
    - pyqode.language_server

about:
  home: https://github.com/open-cogsci/opensesame-extension-language_server
  license: GPLv3
  summary: 'Language-server extension for OpenSesame and Rapunzel'
